In [22]:
import pandas as pd
white_final = pd.read_csv('white_final.csv',sep=',',encoding = "ISO-8859-1")
maclious_final = pd.read_csv('maclious_final.csv',sep=',',encoding = "ISO-8859-1")
sample_data_phish = pd.read_csv('data_phishtank.csv',sep=',',encoding = "ISO-8859-1")
unlabeled_final = pd.read_csv('unlabeled_final.csv',sep=',',encoding = "ISO-8859-1")

In [170]:
unlabeled_final['start_date'][16]

'1996-08-01 00:00:00'

In [14]:
unlabel_final1 = pd.read_csv('status_check_final1.csv',sep=',',encoding = "ISO-8859-1")
unlabel_final2 = pd.read_csv('status_check_final2.csv',sep=',',encoding = "ISO-8859-1")
unlabel_final3 = pd.read_csv('status_check_final3.csv',sep=',',encoding = "ISO-8859-1")
unlabel_final4 = pd.read_csv('status_check_final4.csv',sep=',',encoding = "ISO-8859-1")

In [15]:
unlabel_final = unlabel_final1.append(unlabel_final2, ignore_index=True)
unlabel_final = unlabel_final.append(unlabel_final3, ignore_index=True)
unlabel_final = unlabel_final.append(unlabel_final4, ignore_index=True)

In [16]:
unlabel_final.head()

,Unified_url,Reachable_URL,Way_back_archived,Freenom_top_level_domain,Previous_malicious_top_level_domain_TLD,Name_length,Wrong_spell_List,Longest_word_ratio,Special_mark,sub_domain,Contain_Weried_number_combination,levenshtein_distance,Alexa_rank,Status_code,Shortening_service,start_date,end_date
0,http://coronavirusemploymentservices.com,0,0,0,0,6,0,0.050000,0,2,0,14,0,200,0,0,0
1,http://coronavirusen.com,0,0,0,0,5,0,0.083333,0,2,0,3,0,"[Errno 8] nodename nor servname provided, or n...",0,0,0
2,http://coronavirusencasa.com,0,0,0,0,6,0,0.071429,0,2,0,5,0,"[Errno 8] nodename nor servname provided, or n...",0,0,0
3,http://coronavirusencolombia.com,0,0,0,0,6,0,0.062500,0,2,0,8,8926414,404,0,0,0
4,http://coronavirusend.com,0,0,0,0,5,0,0.080000,0,2,0,3,0,200,0,0,0

In [17]:
phishtank_final1 = pd.read_csv('phishtank_status_check_final1.csv',sep=',',encoding = "ISO-8859-1")
phishtank_final2 = pd.read_csv('phishtank_status_check_final2.csv',sep=',',encoding = "ISO-8859-1")
phish_tank_final = phishtank_final1.append(phishtank_final2, ignore_index=True)

In [18]:
unlabel_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229489 entries, 0 to 229488
Data columns (total 17 columns):
Unified_url                                229489 non-null object
Reachable_URL                              229489 non-null int64
Way_back_archived                          229489 non-null int64
Freenom_top_level_domain                   229489 non-null int64
Previous_malicious_top_level_domain_TLD    229489 non-null int64
Name_length                                229489 non-null int64
Wrong_spell_List                           229489 non-null int64
Longest_word_ratio                         229489 non-null float64
Special_mark                               229489 non-null int64
sub_domain                                 229489 non-null int64
Contain_Weried_number_combination          229489 non-null int64
levenshtein_distance                       229489 non-null int64
Alexa_rank                                 229489 non-null int64
Status_code                                229489 non-null object
Shortening_service                         229489 non-null int64
start_date                                 229466 non-null object
end_date                                   229184 non-null object
dtypes: float64(1), int64(12), object(4)
memory usage: 29.8+ MB

In [19]:
phish_tank_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98251 entries, 0 to 98250
Data columns (total 17 columns):
Unified_url                                98251 non-null object
Reachable_URL                              98251 non-null int64
Way_back_archived                          98251 non-null int64
Freenom_top_level_domain                   98251 non-null int64
Previous_malicious_top_level_domain_TLD    98251 non-null int64
Name_length                                98251 non-null int64
Wrong_spell_List                           98251 non-null int64
Longest_word_ratio                         98251 non-null float64
Special_mark                               98251 non-null int64
sub_domain                                 98251 non-null int64
Contain_Weried_number_combination          98251 non-null int64
levenshtein_distance                       98251 non-null int64
Alexa_rank                                 98251 non-null int64
Status_code                                98251 non-null object
Shortening_service                         98251 non-null int64
start_date                                 98251 non-null object
end_date                                   98251 non-null object
dtypes: float64(1), int64(12), object(4)
memory usage: 12.7+ MB

In [27]:
import urllib.request, urllib.error
from tqdm import tqdm
import http
from socket import timeout
check_white_final = []
getattr(tqdm, '_instances', {}).clear()
for i in tqdm(white_final['Unified_url']):
    url = i
    try:
        conn = urllib.request.urlopen(url,timeout = 10)
    except urllib.error.HTTPError as e:
        check_white_final.append(e.code)
    except urllib.error.URLError as e:
        # Not an HTTP-specific error (e.g. connection refused)
        # ...
        check_white_final.append(e.reason)
    except ConnectionError as e:
        check_white_final.append(e)
    except timeout:
         check_white_final.append('time out')
    except http.client.BadStatusLine as e:
        check_white_final.append('unknown structure')
    except http.client.InvalidURL as e:
        check_white_final.append('url error')
    else:
        # 200
        # ...
        check_white_final.append(200)

100%|██████████| 98/98 [04:01<00:00,  2.47s/it]

In [25]:
import urllib.request, urllib.error
from socket import timeout
check_maclious_final = []
getattr(tqdm, '_instances', {}).clear()
for i in tqdm(maclious_final['Unified_url']):
    url = i
    try:
        conn = urllib.request.urlopen(url,timeout = 10)
    except urllib.error.HTTPError as e:
        check_maclious_final.append(e.code)
    except urllib.error.URLError as e:
        # Not an HTTP-specific error (e.g. connection refused)
        # ...
        check_maclious_final.append(e.reason)
    except ConnectionError as e:
        check_maclious_final.append(e)
    except timeout:
         check_maclious_final.append('time out')
    except http.client.BadStatusLine as e:
        check_maclious_final.append('unknown structure')
    except http.client.InvalidURL as e:
        check_maclious_final.append('url error')
    else:
        # 200
        # ...
        check_maclious_final.append(200)

  4%|▍         | 15/394 [00:50<21:03,  3.33s/it]
100%|██████████| 394/394 [14:57<00:00,  2.28s/it]

In [28]:
maclious_final['Status_code'] = check_maclious_final
white_final['Status_code'] = check_white_final

In [ ]:
white_final = white_final.rename(columns = {'word_dic':'Longest_word_ratio'})
maclious_final = maclious_final.rename(columns = {'word_dic':'Longest_word_ratio'})

In [239]:
unlabel_final.to_csv('unlabled_data_final_version.csv',index=False,header=True)
phish_tank_final.to_csv('phish_tank_final_version.csv',index=False,header=True)
maclious_final.to_csv('confirmed_CovidURL_final_version.csv',index=False,header=True)
white_final.to_csv('Confirmed_whitelist_final_version.csv',index=False,header=True)

In [104]:
maclious_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 394 entries, 0 to 393
Data columns (total 17 columns):
Unified_url                                394 non-null object
Reachable_URL                              394 non-null int64
Way_back_archived                          394 non-null int64
Freenom_top_level_domain                   394 non-null int64
Previous_malicious_top_level_domain_TLD    394 non-null int64
Name_length                                394 non-null int64
Wrong_spell_List                           394 non-null int64
Longest_word_ratio                         394 non-null float64
Special_mark                               394 non-null int64
sub_domain                                 394 non-null int64
Contain_IP_Adress                          394 non-null int64
levenshtein_distance                       394 non-null int64
Alexa_rank                                 394 non-null int64
Status_code                                394 non-null object
Shortening service                         394 non-null int64
start_date                                 394 non-null object
end_date                                   394 non-null object
dtypes: float64(1), int64(12), object(4)
memory usage: 52.4+ KB

In [35]:
unlabel_final.head()

,Unified_url,Reachable_URL,Way_back_archived,Freenom_top_level_domain,Previous_malicious_top_level_domain_TLD,Name_length,Wrong_spell_List,Longest_word_ratio,Special_mark,sub_domain,Contain_Weried_number_combination,levenshtein_distance,Alexa_rank,Status_code,Shortening_service,start_date,end_date
0,http://coronavirusemploymentservices.com,0,0,0,0,6,0,0.050000,0,2,0,14,0,200,0,0,0
1,http://coronavirusen.com,0,0,0,0,5,0,0.083333,0,2,0,3,0,"[Errno 8] nodename nor servname provided, or n...",0,0,0
2,http://coronavirusencasa.com,0,0,0,0,6,0,0.071429,0,2,0,5,0,"[Errno 8] nodename nor servname provided, or n...",0,0,0
3,http://coronavirusencolombia.com,0,0,0,0,6,0,0.062500,0,2,0,8,8926414,404,0,0,0
4,http://coronavirusend.com,0,0,0,0,5,0,0.080000,0,2,0,3,0,200,0,0,0

In [ ]:
asd = unlabel_final['Status_code']

In [30]:
unified_status_code = []
for i in unlabel_final['Status_code']:
    if i[:32] == '[SSL: CERTIFICATE_VERIFY_FAILED]':
        unified_status_code.append(511)
    else:
        unified_status_code.append(i)
unlabel_final['Status_code'] = unified_status_code

In [31]:
phishtank_status_code = []
maclious_status_code = []
whitelist_status_code = []

for i in phish_tank_final['Status_code']:
    if i[:32] == '[SSL: CERTIFICATE_VERIFY_FAILED]':
        phishtank_status_code.append(511)
    else:
        phishtank_status_code.append(i)
        
for i in maclious_final['Status_code']:
    i = str(i)
    if i[:32] == '[SSL: CERTIFICATE_VERIFY_FAILED]':
        maclious_status_code.append(511)
    else:
        maclious_status_code.append(i)

for i in white_final['Status_code']:
    i = str(i)
    if i[:32] == '[SSL: CERTIFICATE_VERIFY_FAILED]':
        whitelist_status_code.append(511)
    else:
        whitelist_status_code.append(i)

In [32]:
phish_tank_final['Status_code'] = phishtank_status_code
maclious_final['Status_code'] = maclious_status_code
white_final['Status_code'] = whitelist_status_code

In [33]:
status_code_class = unlabel_final.groupby(by=['Status_code'])
temp = status_code_class.size().reset_index()

In [34]:
temp

                                          Status_code      0
0                                                 511   2341
1                                                 200  98026
2                                                 301     58
3                                                 302     50
4                                                 307      2
5                                                 308    723
6                                                 400    729
7                                                 401   1695
8                                                 402    152
9                                                 403   8464
10                                                404  58593
11                                                405      1
12                                                406     12
13                                                408      1
14                                                409     79
15                                                410    227
16                                                412     42
17                                                416      1
18                                                423    273
19                                                424      2
20                                                426      7
21                                                429    144
22                                                433      1
23                                                444      1
24                                                479     10
25                                                500    370
26                                                501      2
27                                                502    675
28                                                503    611
29                                                504    145
30                                                508      4
31                                                510     14
32                                                511      1
33                                                999      9
34      Remote end closed connection without response     59
35                                    [Errno 0] Error     82
36                  [Errno 51] Network is unreachable     57
37                [Errno 54] Connection reset by peer    778
38                     [Errno 60] Operation timed out    424
39                      [Errno 61] Connection refused   1053
40                        [Errno 65] No route to host      2
41  [Errno 8] nodename nor servname provided, or n...  42670
42  [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert ...     91
43  [SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecogni...      1
44  [SSL: WRONG_VERSION_NUMBER] wrong version numb...      2
45     _ssl.c:1059: The handshake operation timed out      9
46                                           time out   5136
47                                          timed out   5657
48                                  unknown structure      3

In [44]:
wrong_string_list = temp['Status_code'][34:]

In [45]:
wrong_string_list[42]

'[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1076)'

In [46]:
wrong_string_list_code = [500,400,451,500,408,599,503,503,500,500,500,598,598,598,405]

In [61]:
def code_unified(templist):
    unified_status_code_final = []
    getattr(tqdm, '_instances', {}).clear()
    for i in tqdm(templist):
        i = str(i)
        if any(i in s for s in wrong_string_list):
            unified_status_code_final.append(wrong_string_list_code[wrong_string_list.index(i)])
        else:
            unified_status_code_final.append(i)
    return unified_status_code_final
unified_status_code_final = code_unified(unlabel_final['Status_code'])

100%|██████████| 229489/229489 [00:00<00:00, 508877.37it/s]

In [62]:
unlabel_final['Status_code'] = unified_status_code_final

In [63]:
status_code_class_final = unlabel_final.groupby(by=['Status_code'])
temp_final = status_code_class_final.size().reset_index()

In [64]:
temp_final

   Status_code      0
0          200  98026
1          301     58
2          302     50
3          307      2
4          308    723
5          400    811
6          401   1695
7          402    152
8          403   8464
9          404  58593
10         405      4
11         406     12
12         408    425
13         409     79
14         410    227
15         412     42
16         416      1
17         423    273
18         424      2
19         426      7
20         429    144
21         433      1
22         444      1
23         451     57
24         479     10
25         500   1301
26         501      2
27         502    675
28         503  43283
29         504    145
30         508      4
31         510     14
32         511   2342
33         598  10802
34         599   1053
35         999      9

In [65]:
phish_tank_unified_status_code_final = []
maclious_unified_status_code_final = []
white_unified_status_code_final = []

        
phish_tank_unified_status_code_final = code_unified(phish_tank_final['Status_code'])
maclious_unified_status_code_final = code_unified(maclious_final['Status_code'])
white_unified_status_code_final = code_unified(white_final['Status_code'])

100%|██████████| 98251/98251 [00:00<00:00, 563278.52it/s]
100%|██████████| 394/394 [00:00<00:00, 399554.10it/s]
100%|██████████| 98/98 [00:00<00:00, 172272.34it/s]

In [66]:
phish_tank_final['Status_code'] = phish_tank_unified_status_code_final
maclious_final['Status_code'] = maclious_unified_status_code_final
white_final['Status_code'] = white_unified_status_code_final

In [67]:
phish_status_code_class_final = phish_tank_final.groupby(by=['Status_code'])
temp_final1 = phish_status_code_class_final.size().reset_index()
temp_final1

                                          Status_code      0
0                                                 400    689
1                                                 451   1259
2                                                 500   2156
3                                                 503  36770
4                                                 598   8048
5                                                 599   4225
6                                                 200  18070
7                                                 301      6
8                                                 302     17
9                                                 308      1
10                                                400     40
11                                                401    142
12                                                402      2
13                                                403   4704
14                                                404   3951
15                                                405      2
16                                                406      8
17                                                408      2
18                                                410   6088
19                                                412      1
20                                                421      1
21                                                423     10
22                                                424      7
23                                                429      2
24                                                444      1
25                                                451      6
26                                                500    435
27                                                502     33
28                                                503    208
29                                                504     10
30                                                508      2
31                                                510      2
32                                                511  11077
33                                                523      1
34                                                999      3
35  [SSL: REUSE_CERT_TYPE_NOT_ZERO] unsolicited ex...      1
36  [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 ale...    269
37  [SSL: UNSUPPORTED_PROTOCOL] unsupported protoc...      1
38                                          url error      1

In [68]:
temp_list = []
for i in phish_tank_final['Status_code']:
    i = str(i)
    if i[0] == '[' or i[0] == 'u':
        temp_list.append(500)
    else:
        temp_list.append(i)
phish_tank_final['Status_code'] = temp_list

In [69]:
phish_tank_final['Status_code'] = phish_tank_final['Status_code'].astype(int)

In [70]:
phish_status_code_class_final = phish_tank_final.groupby(by=['Status_code'])
temp_final1 = phish_status_code_class_final.size().reset_index()
temp_final1

    Status_code      0
0           200  18070
1           301      6
2           302     17
3           308      1
4           400    729
5           401    142
6           402      2
7           403   4704
8           404   3951
9           405      2
10          406      8
11          408      2
12          410   6088
13          412      1
14          421      1
15          423     10
16          424      7
17          429      2
18          444      1
19          451   1265
20          500   2863
21          502     33
22          503  36978
23          504     10
24          508      2
25          510      2
26          511  11077
27          523      1
28          598   8048
29          599   4225
30          999      3

In [72]:
white_status_code_class_final = white_final.groupby(by=['Status_code'])
temp_final2 = white_status_code_class_final.size().reset_index()
temp_final2

  Status_code   0
0         503  12
1         598  15
2         200  56
3         301   1
4         403   7
5         511   7

In [73]:
maclious_status_code_class_final = maclious_final.groupby(by=['Status_code'])
temp_final3 = maclious_status_code_class_final.size().reset_index()
temp_final3

   Status_code    0
0          451    1
1          503  220
2          598   68
3          599    3
4          200   77
5          400    2
6          401    1
7          403   12
8          404    5
9          410    1
10         500    2
11         999    2

In [74]:
with open('temp1.txt', 'w') as filehandle:
    for listitem in unlabel_final['Status_code']:
        filehandle.write('%s\n' % listitem)

In [75]:
with open('temp2.txt', 'w') as filehandle:
    for listitem in phish_tank_final['Status_code']:
        filehandle.write('%s\n' % listitem)
with open('temp3.txt', 'w') as filehandle:
    for listitem in white_final['Status_code']:
        filehandle.write('%s\n' % listitem)
with open('temp4.txt', 'w') as filehandle:
    for listitem in maclious_final['Status_code']:
        filehandle.write('%s\n' % listitem)

In [127]:
def Unified_alexa_rank(alexa_list):
    unified_list = []
    for i in alexa_list:
        if i != 0:
            unified_list.append(1)
        else:
            unified_list.append(0)
    return unified_list

In [414]:
unlabel_final['Alexa_rank'] = Unified_alexa_rank(unlabel_final['Alexa_rank'])
phish_tank_final['Alexa_rank'] = Unified_alexa_rank(phish_tank_final['Alexa_rank'])
maclious_final['Alexa_rank'] = Unified_alexa_rank(maclious_final['Alexa_rank'])
white_final['Alexa_rank'] = Unified_alexa_rank(white_final['Alexa_rank'])

In [260]:
unlabel_final['start_date'].isnull().sum()

23

In [269]:
import numpy as np
unlabel_final['start_date'] = unlabel_final['start_date'].replace(np.nan, 0)

In [270]:
unlabel_final['start_date'].isnull().sum()

0

In [261]:
unlabel_final['end_date'].isnull().sum()

304

In [272]:
unlabel_final['end_date'] = unlabel_final['end_date'].replace(np.nan, 0)

In [266]:
unlabel_final['end_date'].isnull().sum()

0

In [276]:
end_temp = []
for i in unlabel_final['end_date']:
    if i == 'nan':
        end_temp.append(0)
    else:
        end_temp.append(i)
unlabel_final['end_date'] = end_temp

In [278]:
start_temp = []
for i in unlabel_final['start_date']:
    if i == 'nan':
        start_temp.append(0)
    else:
        start_temp.append(i)
unlabel_final['start_date'] = start_temp

In [296]:
import datetime
def calculate_age(start,end):
    age_list = []
    getattr(tqdm, '_instances', {}).clear()
    for i in tqdm(range(len(start))):
        start[i] = str(start[i])
        end[i] = str(end[i])
        if len(start[i]) > 1 and len(end[i]) >1:
            start_date = datetime.datetime(int(start[i][:4]), int(start[i][5:7]), int(start[i][8:10]))
            end_date = datetime.datetime(int(end[i][:4]), int(end[i][5:7]), int(end[i][8:10]))
            age =  end_date - start_date 
            age_list.append(age)
        else:
            age_list.append(0)
    return age_list
Unlabeled_age_list = calculate_age(unlabel_final['start_date'],unlabel_final['end_date'])

  0%|          | 0/229489 [00:00<?, ?it/s]/Users/jackline/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/jackline/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
  1%|          | 2346/229489 [08:05<13:03:59,  4.83it/s]
100%|██████████| 229489/229489 [6:49:27<00:00,  9.34it/s]

In [321]:
import datetime
def calculate_age(start,end):
    age_list = []
    getattr(tqdm, '_instances', {}).clear()
    for i in tqdm(range(len(start))):
        start[i] = str(start[i])
        end[i] = str(end[i])
        if len(start[i]) > 1 and len(end[i]) >1:
            start_date = datetime.datetime(int(start[i][:4]), int(start[i][5:7]), int(start[i][8:10]))
            end_date = datetime.datetime(int(end[i][:4]), int(end[i][5:7]), int(end[i][8:10]))
            age =  end_date - start_date 
            age_list.append(age)
        else:
            age_list.append(0)
    return age_list
phishtank_age_list = calculate_age(phish_tank_final['start_date'],phish_tank_final['end_date'])

  0%|          | 0/98251 [00:00<?, ?it/s]/Users/jackline/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/jackline/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
100%|██████████| 98251/98251 [2:55:06<00:00,  9.35it/s]

In [323]:
def calculate_age(start,end):
    age_list = []
    getattr(tqdm, '_instances', {}).clear()
    for i in tqdm(range(len(start))):
        start[i] = str(start[i])
        end[i] = str(end[i])
        if len(start[i]) > 1 and len(end[i]) >1:
            start_date = datetime.datetime(int(start[i][:4]), int(start[i][5:7]), int(start[i][8:10]))
            end_date = datetime.datetime(int(end[i][:4]), int(end[i][5:7]), int(end[i][8:10]))
            age =  end_date - start_date 
            age_list.append(age)
        else:
            age_list.append(0)
    return age_list

maclious_age_list = calculate_age(maclious_final['start_date'],maclious_final['end_date'])

  0%|          | 0/394 [00:00<?, ?it/s]/Users/jackline/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/jackline/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

100%|██████████| 394/394 [00:42<00:00,  9.28it/s]

In [336]:
def calculate_age(start,end):
    age_list = []
    getattr(tqdm, '_instances', {}).clear()
    for i in tqdm(range(len(start))):
        start[i] = str(start[i])
        end[i] = str(end[i])
        if len(start[i]) > 1 and len(end[i]) >1:
            start_date = datetime.datetime(int(start[i][:4]), int(start[i][5:7]), int(start[i][8:10]))
            end_date = datetime.datetime(int(end[i][:4]), int(end[i][5:7]), int(end[i][8:10]))
            age =  end_date - start_date 
            age_list.append(age)
        else:
            age_list.append(0)
    return age_list
white_age_list = calculate_age(white_final['start_date'],white_final['end_date'])

  0%|          | 0/98 [00:00<?, ?it/s]/Users/jackline/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/jackline/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

100%|██████████| 98/98 [00:11<00:00,  8.63it/s]

In [341]:
def datetime_conversion(age_list):
    long_list = []
    for i in age_list:
        if i!=0:
            i = i.days
            long_list.append(i)
        else:
            long_list.append(i)
    return long_list
temp1 = datetime_conversion(white_age_list)
temp2 = datetime_conversion(maclious_age_list)
temp3 = datetime_conversion(phishtank_age_list)
temp4 = datetime_conversion(Unlabeled_age_list)

In [417]:
unlabel_final['site_age(days)'] = temp4
phish_tank_final['site_age(days)'] = temp3
maclious_final['site_age(days)'] = temp2
white_final['site_age(days)'] = temp1

In [421]:
unlabel_final = unlabel_final.drop(columns = ['site_age'])
phish_tank_final = phish_tank_final.drop(columns = ['site_age'])
maclious_final = maclious_final.drop(columns = ['site_age'])
white_final = white_final.drop(columns = ['site_age'])

In [422]:
white_final.head()

,Unified_url,Reachable_URL,Way_back_archived,Freenom_top_level_domain,Previous_malicious_top_level_domain_TLD,Name_length,Wrong_spell_List,word_dic,Special_mark,sub_domain,Contain_IP_Adress,levenshtein_distance,Alexa_rank,Status_code,Shortening service,start_date,end_date,site_age(days)
0,https://akkure4covid.com,1,1,0,0,7,0,0.090909,0,1,0,5,0,0,0,2020-02-28 00:00:00,2021-02-28 00:00:00,366
1,https://api.contracovid.com.br,1,0,0,0,7,0,0.071429,0,3,0,10,0,200,0,0,0,0
2,https://app.contracovid.com.br,1,0,0,0,7,0,0.071429,0,3,0,10,0,200,0,0,0,0
3,https://auxilio.caixa.gov.br,1,1,0,0,8,0,0.076923,0,3,0,13,1,200,0,0,0,0
4,https://bag-coronavirus.ch,1,1,0,0,4,0,0.083333,1,1,0,6,1,200,0,0,0,0

In [433]:
white_finals = pd.read_csv('white_final.csv',sep=',',encoding = "ISO-8859-1")
maclious_finals = pd.read_csv('maclious_final.csv',sep=',',encoding = "ISO-8859-1")
sample_data_phishs = pd.read_csv('data_phishtank.csv',sep=',',encoding = "ISO-8859-1")
unlabeled_finals = pd.read_csv('unlabeled_final.csv',sep=',',encoding = "ISO-8859-1")

In [434]:
unlabel_final['start_date'] = unlabeled_finals['start_date']
phish_tank_final['start_date'] = sample_data_phishs['start_date']
maclious_final['start_date'] = maclious_finals['start_date']
white_final['start_date'] = white_finals['start_date']
unlabel_final['end_date'] = unlabeled_finals['end_date']
phish_tank_final['end_date'] = sample_data_phishs['end_date']
maclious_final['end_date'] = maclious_finals['end_date']
white_final['end_date'] = white_finals['end_date']

In [439]:
def year_extraction(date_time):
    year_list = []
    for i in date_time:
        i = str(i)
        if i!= 0: 
            year = i[:4]
            year_list.append(year)
        else:
            year_list.append(0)
    return year_list

In [440]:
year1 = year_extraction(unlabel_final['start_date'])
year2 = year_extraction(phish_tank_final['start_date'])
year3 = year_extraction(maclious_final['start_date'])
year4 = year_extraction(white_final['start_date'])

In [441]:
year5 = year_extraction(unlabel_final['end_date'])
year6 = year_extraction(phish_tank_final['end_date'])
year7 = year_extraction(maclious_final['end_date'])
year8 = year_extraction(white_final['end_date'])

In [442]:
unlabel_final['start_date'] = year1
phish_tank_final['start_date'] = year2
maclious_final['start_date'] = year3
white_final['start_date'] = year4
unlabel_final['end_date'] = year5
phish_tank_final['end_date'] = year6
maclious_final['end_date'] = year7
white_final['end_date'] = year8

In [443]:
white_final.head()

,Unified_url,Reachable_URL,Way_back_archived,Freenom_top_level_domain,Previous_malicious_top_level_domain_TLD,Name_length,Wrong_spell_List,word_dic,Special_mark,sub_domain,Contain_IP_Adress,levenshtein_distance,Alexa_rank,Status_code,Shortening service,start_date,end_date,site_age(days)
0,https://akkure4covid.com,1,1,0,0,7,0,0.090909,0,1,0,5,0,0,0,2020,2021,366
1,https://api.contracovid.com.br,1,0,0,0,7,0,0.071429,0,3,0,10,0,200,0,0,0,0
2,https://app.contracovid.com.br,1,0,0,0,7,0,0.071429,0,3,0,10,0,200,0,0,0,0
3,https://auxilio.caixa.gov.br,1,1,0,0,8,0,0.076923,0,3,0,13,1,200,0,0,0,0
4,https://bag-coronavirus.ch,1,1,0,0,4,0,0.083333,1,1,0,6,1,200,0,0,0,0

In [458]:
unlabel_final.to_csv('unlabled_data_final_version.csv',index=False,header=True)
phish_tank_final.to_csv('phish_tank_final_version.csv',index=False,header=True)
maclious_final.to_csv('confirmed_CovidURL_final_version.csv',index=False,header=True)
white_final.to_csv('Confirmed_whitelist_final_version.csv',index=False,header=True)

In [473]:
unlabel_final.tail()

,Unified_url,Reachable_URL,Way_back_archived,Freenom_top_level_domain,Previous_malicious_top_level_domain_TLD,Name_length,Wrong_spell_List,Longest_word_ratio,Special_mark,sub_domain,Contain_Weried_number_combination,levenshtein_distance,Alexa_rank,Status_code,Shortening_service,start_date,end_date,site_age(days)
229484,http://ccolo.pro.ivirus.ru,1,0,0,0,7,0,0.083333,0,3,0,11,1,404,0,0,0,0
229485,http://ccooxxc0001-microsofterrorfound-virusfo...,0,0,0,0,13,0,0.039216,1,1,0,32,0,0,0,0,0,0
229486,http://ccooxxc0041-microsofterrorfound-virusfo...,1,0,0,0,12,0,0.040000,1,1,0,31,0,200,0,0,0,0
229487,http://ccorona-hub.de,1,0,0,0,5,0,0.105263,1,1,0,7,0,200,0,0,0,0
229488,http://ccoronavirus.co.uk,1,0,0,0,5,0,0.086957,0,2,0,6,0,200,0,0,0,0

In [2]:
import re 

# for i in re.finditer('/.','http://ccoloproivirus.ru'):
url = 'http://www.ccoloproivirus.ru'
position = [m.start() for m in re.finditer('[.]',url)]
print(position)
if len(position) > 1:
    char = url[position[0]:][1:]
    print(char)
else:
    hostname = url
    pattern = "https://|http://|www.|https://www.|http://www."
    pre_pattern_match = re.search(pattern, hostname)
    if pre_pattern_match:
        hostname = hostname[pre_pattern_match.end():]
        post_pattern_match = re.search("/", hostname)
        if post_pattern_match:
            hostname = hostname[:post_pattern_match.start()]
        char = hostname
print(char)

[10, 25]
ccoloproivirus.ru
ccoloproivirus.ru

In [1]:
import pandas as pd
unlabeled_final = pd.read_csv('unlabled_data_final_version.csv',sep=',',encoding = "ISO-8859-1")
phish_tank_final = pd.read_csv('phish_tank_final_version.csv',sep=',',encoding = "ISO-8859-1")
confirmed_maclious_final = pd.read_csv('confirmed_CovidURL_final_version.csv',sep=',',encoding = "ISO-8859-1")
white_list_final = pd.read_csv('Confirmed_whitelist_final_version.csv',sep=',',encoding = "ISO-8859-1")

In [6]:
import subprocess
import re 
from tqdm import tqdm
def dig_wildCard_domain(url_list):
    wildcard_subdomain = []
    getattr(tqdm, '_instances', {}).clear()
    for url in tqdm(url_list):
#         print(url)
        hostname = url
        pattern = "https://|http://|www.|https://www.|http://www."
        pre_pattern_match = re.search(pattern, hostname)
        if pre_pattern_match:
            hostname = hostname[pre_pattern_match.end():]
            post_pattern_match = re.search("/", hostname)
            if post_pattern_match:
                hostname = hostname[:post_pattern_match.start()]
            char = hostname
        if char[:3] == 'www':
            position = [m.start() for m in re.finditer('[.]',url)]
            char = url[position[0]:][1:]
            search_char = '*' + '.' + char
#             print(search_char)
            out = subprocess.Popen(['dig', '+short', search_char], 
                   stdout=subprocess.PIPE, 
                   stderr=subprocess.STDOUT)
            stdout,stderr = out.communicate()
            if len(stdout)!= 0:
                wildcard_subdomain.append(1)
            else:
                wildcard_subdomain.append(0)
        else:   
            search_char = '*' + '.' + char
#             print(search_char)
            out = subprocess.Popen(['dig', '+short', search_char], 
                   stdout=subprocess.PIPE, 
                   stderr=subprocess.STDOUT)
            stdout,stderr = out.communicate()
#             print(stdout)
            if len(stdout)!= 0:
                wildcard_subdomain.append(1)
            else:
                wildcard_subdomain.append(0)
    return wildcard_subdomain

In [7]:
wildcard_subdomain_white = dig_wildCard_domain(white_list_final['Unified_url'])

100%|██████████| 98/98 [00:57<00:00,  1.71it/s]

In [8]:
print(wildcard_subdomain_white)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]

In [9]:
wildcard_subdomain_maclious = dig_wildCard_domain(confirmed_maclious_final['Unified_url'])

100%|██████████| 394/394 [00:54<00:00,  7.21it/s]

In [10]:
wildcard_subdomain_phishtank = dig_wildCard_domain(phish_tank_final['Unified_url'])

100%|██████████| 98251/98251 [11:37:28<00:00,  2.35it/s]

In [11]:
with open('phishtank_wildcard.txt', 'w') as filehandle:
    for listitem in wildcard_subdomain_phishtank:
        filehandle.write('%s\n' % listitem)

In [12]:
with open('white_wildcard.txt', 'w') as filehandle:
    for listitem in wildcard_subdomain_white:
        filehandle.write('%s\n' % listitem)

In [13]:
with open('maclious_wildcard.txt', 'w') as filehandle:
    for listitem in wildcard_subdomain_maclious:
        filehandle.write('%s\n' % listitem)